/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GeneralDataRouteImport } from './routes/general-data'
import { Route as IndexRouteImport } from './routes/index'
import { Route as P2hTechnicalParametersRouteImport } from './routes/p2h/technical-parameters'
import { Route as P2hSummaryOfResultsRouteImport } from './routes/p2h/summary-of-results'
import { Route as P2hEconomicParametersRouteImport } from './routes/p2h/economic-parameters'
import { Route as P2gTechnicalParametersRouteImport } from './routes/p2g/technical-parameters'
import { Route as P2gSummaryOfResultsRouteImport } from './routes/p2g/summary-of-results'
import { Route as P2gEconomicParametersRouteImport } from './routes/p2g/economic-parameters'
import { Route as DsrTechnicalParametersRouteImport } from './routes/dsr/technical-parameters'
import { Route as DsrSummaryOfResultsRouteImport } from './routes/dsr/summary-of-results'
import { Route as DsrEconomicParametersRouteImport } from './routes/dsr/economic-parameters'
import { Route as BeksTechnicalParametersRouteImport } from './routes/beks/technical-parameters'
import { Route as BeksSummaryOfResultsRouteImport } from './routes/beks/summary-of-results'
import { Route as BeksEconomicParametersRouteImport } from './routes/beks/economic-parameters'

const GeneralDataRoute = GeneralDataRouteImport.update({
  id: '/general-data',
  path: '/general-data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const P2hTechnicalParametersRoute = P2hTechnicalParametersRouteImport.update({
  id: '/p2h/technical-parameters',
  path: '/p2h/technical-parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const P2hSummaryOfResultsRoute = P2hSummaryOfResultsRouteImport.update({
  id: '/p2h/summary-of-results',
  path: '/p2h/summary-of-results',
  getParentRoute: () => rootRouteImport,
} as any)
const P2hEconomicParametersRoute = P2hEconomicParametersRouteImport.update({
  id: '/p2h/economic-parameters',
  path: '/p2h/economic-parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const P2gTechnicalParametersRoute = P2gTechnicalParametersRouteImport.update({
  id: '/p2g/technical-parameters',
  path: '/p2g/technical-parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const P2gSummaryOfResultsRoute = P2gSummaryOfResultsRouteImport.update({
  id: '/p2g/summary-of-results',
  path: '/p2g/summary-of-results',
  getParentRoute: () => rootRouteImport,
} as any)
const P2gEconomicParametersRoute = P2gEconomicParametersRouteImport.update({
  id: '/p2g/economic-parameters',
  path: '/p2g/economic-parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const DsrTechnicalParametersRoute = DsrTechnicalParametersRouteImport.update({
  id: '/dsr/technical-parameters',
  path: '/dsr/technical-parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const DsrSummaryOfResultsRoute = DsrSummaryOfResultsRouteImport.update({
  id: '/dsr/summary-of-results',
  path: '/dsr/summary-of-results',
  getParentRoute: () => rootRouteImport,
} as any)
const DsrEconomicParametersRoute = DsrEconomicParametersRouteImport.update({
  id: '/dsr/economic-parameters',
  path: '/dsr/economic-parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const BeksTechnicalParametersRoute = BeksTechnicalParametersRouteImport.update({
  id: '/beks/technical-parameters',
  path: '/beks/technical-parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const BeksSummaryOfResultsRoute = BeksSummaryOfResultsRouteImport.update({
  id: '/beks/summary-of-results',
  path: '/beks/summary-of-results',
  getParentRoute: () => rootRouteImport,
} as any)
const BeksEconomicParametersRoute = BeksEconomicParametersRouteImport.update({
  id: '/beks/economic-parameters',
  path: '/beks/economic-parameters',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/general-data': typeof GeneralDataRoute
  '/beks/economic-parameters': typeof BeksEconomicParametersRoute
  '/beks/summary-of-results': typeof BeksSummaryOfResultsRoute
  '/beks/technical-parameters': typeof BeksTechnicalParametersRoute
  '/dsr/economic-parameters': typeof DsrEconomicParametersRoute
  '/dsr/summary-of-results': typeof DsrSummaryOfResultsRoute
  '/dsr/technical-parameters': typeof DsrTechnicalParametersRoute
  '/p2g/economic-parameters': typeof P2gEconomicParametersRoute
  '/p2g/summary-of-results': typeof P2gSummaryOfResultsRoute
  '/p2g/technical-parameters': typeof P2gTechnicalParametersRoute
  '/p2h/economic-parameters': typeof P2hEconomicParametersRoute
  '/p2h/summary-of-results': typeof P2hSummaryOfResultsRoute
  '/p2h/technical-parameters': typeof P2hTechnicalParametersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/general-data': typeof GeneralDataRoute
  '/beks/economic-parameters': typeof BeksEconomicParametersRoute
  '/beks/summary-of-results': typeof BeksSummaryOfResultsRoute
  '/beks/technical-parameters': typeof BeksTechnicalParametersRoute
  '/dsr/economic-parameters': typeof DsrEconomicParametersRoute
  '/dsr/summary-of-results': typeof DsrSummaryOfResultsRoute
  '/dsr/technical-parameters': typeof DsrTechnicalParametersRoute
  '/p2g/economic-parameters': typeof P2gEconomicParametersRoute
  '/p2g/summary-of-results': typeof P2gSummaryOfResultsRoute
  '/p2g/technical-parameters': typeof P2gTechnicalParametersRoute
  '/p2h/economic-parameters': typeof P2hEconomicParametersRoute
  '/p2h/summary-of-results': typeof P2hSummaryOfResultsRoute
  '/p2h/technical-parameters': typeof P2hTechnicalParametersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/general-data': typeof GeneralDataRoute
  '/beks/economic-parameters': typeof BeksEconomicParametersRoute
  '/beks/summary-of-results': typeof BeksSummaryOfResultsRoute
  '/beks/technical-parameters': typeof BeksTechnicalParametersRoute
  '/dsr/economic-parameters': typeof DsrEconomicParametersRoute
  '/dsr/summary-of-results': typeof DsrSummaryOfResultsRoute
  '/dsr/technical-parameters': typeof DsrTechnicalParametersRoute
  '/p2g/economic-parameters': typeof P2gEconomicParametersRoute
  '/p2g/summary-of-results': typeof P2gSummaryOfResultsRoute
  '/p2g/technical-parameters': typeof P2gTechnicalParametersRoute
  '/p2h/economic-parameters': typeof P2hEconomicParametersRoute
  '/p2h/summary-of-results': typeof P2hSummaryOfResultsRoute
  '/p2h/technical-parameters': typeof P2hTechnicalParametersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/general-data'
    | '/beks/economic-parameters'
    | '/beks/summary-of-results'
    | '/beks/technical-parameters'
    | '/dsr/economic-parameters'
    | '/dsr/summary-of-results'
    | '/dsr/technical-parameters'
    | '/p2g/economic-parameters'
    | '/p2g/summary-of-results'
    | '/p2g/technical-parameters'
    | '/p2h/economic-parameters'
    | '/p2h/summary-of-results'
    | '/p2h/technical-parameters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/general-data'
    | '/beks/economic-parameters'
    | '/beks/summary-of-results'
    | '/beks/technical-parameters'
    | '/dsr/economic-parameters'
    | '/dsr/summary-of-results'
    | '/dsr/technical-parameters'
    | '/p2g/economic-parameters'
    | '/p2g/summary-of-results'
    | '/p2g/technical-parameters'
    | '/p2h/economic-parameters'
    | '/p2h/summary-of-results'
    | '/p2h/technical-parameters'
  id:
    | '__root__'
    | '/'
    | '/general-data'
    | '/beks/economic-parameters'
    | '/beks/summary-of-results'
    | '/beks/technical-parameters'
    | '/dsr/economic-parameters'
    | '/dsr/summary-of-results'
    | '/dsr/technical-parameters'
    | '/p2g/economic-parameters'
    | '/p2g/summary-of-results'
    | '/p2g/technical-parameters'
    | '/p2h/economic-parameters'
    | '/p2h/summary-of-results'
    | '/p2h/technical-parameters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneralDataRoute: typeof GeneralDataRoute
  BeksEconomicParametersRoute: typeof BeksEconomicParametersRoute
  BeksSummaryOfResultsRoute: typeof BeksSummaryOfResultsRoute
  BeksTechnicalParametersRoute: typeof BeksTechnicalParametersRoute
  DsrEconomicParametersRoute: typeof DsrEconomicParametersRoute
  DsrSummaryOfResultsRoute: typeof DsrSummaryOfResultsRoute
  DsrTechnicalParametersRoute: typeof DsrTechnicalParametersRoute
  P2gEconomicParametersRoute: typeof P2gEconomicParametersRoute
  P2gSummaryOfResultsRoute: typeof P2gSummaryOfResultsRoute
  P2gTechnicalParametersRoute: typeof P2gTechnicalParametersRoute
  P2hEconomicParametersRoute: typeof P2hEconomicParametersRoute
  P2hSummaryOfResultsRoute: typeof P2hSummaryOfResultsRoute
  P2hTechnicalParametersRoute: typeof P2hTechnicalParametersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/general-data': {
      id: '/general-data'
      path: '/general-data'
      fullPath: '/general-data'
      preLoaderRoute: typeof GeneralDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2h/technical-parameters': {
      id: '/p2h/technical-parameters'
      path: '/p2h/technical-parameters'
      fullPath: '/p2h/technical-parameters'
      preLoaderRoute: typeof P2hTechnicalParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2h/summary-of-results': {
      id: '/p2h/summary-of-results'
      path: '/p2h/summary-of-results'
      fullPath: '/p2h/summary-of-results'
      preLoaderRoute: typeof P2hSummaryOfResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2h/economic-parameters': {
      id: '/p2h/economic-parameters'
      path: '/p2h/economic-parameters'
      fullPath: '/p2h/economic-parameters'
      preLoaderRoute: typeof P2hEconomicParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2g/technical-parameters': {
      id: '/p2g/technical-parameters'
      path: '/p2g/technical-parameters'
      fullPath: '/p2g/technical-parameters'
      preLoaderRoute: typeof P2gTechnicalParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2g/summary-of-results': {
      id: '/p2g/summary-of-results'
      path: '/p2g/summary-of-results'
      fullPath: '/p2g/summary-of-results'
      preLoaderRoute: typeof P2gSummaryOfResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2g/economic-parameters': {
      id: '/p2g/economic-parameters'
      path: '/p2g/economic-parameters'
      fullPath: '/p2g/economic-parameters'
      preLoaderRoute: typeof P2gEconomicParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsr/technical-parameters': {
      id: '/dsr/technical-parameters'
      path: '/dsr/technical-parameters'
      fullPath: '/dsr/technical-parameters'
      preLoaderRoute: typeof DsrTechnicalParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsr/summary-of-results': {
      id: '/dsr/summary-of-results'
      path: '/dsr/summary-of-results'
      fullPath: '/dsr/summary-of-results'
      preLoaderRoute: typeof DsrSummaryOfResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsr/economic-parameters': {
      id: '/dsr/economic-parameters'
      path: '/dsr/economic-parameters'
      fullPath: '/dsr/economic-parameters'
      preLoaderRoute: typeof DsrEconomicParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beks/technical-parameters': {
      id: '/beks/technical-parameters'
      path: '/beks/technical-parameters'
      fullPath: '/beks/technical-parameters'
      preLoaderRoute: typeof BeksTechnicalParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beks/summary-of-results': {
      id: '/beks/summary-of-results'
      path: '/beks/summary-of-results'
      fullPath: '/beks/summary-of-results'
      preLoaderRoute: typeof BeksSummaryOfResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beks/economic-parameters': {
      id: '/beks/economic-parameters'
      path: '/beks/economic-parameters'
      fullPath: '/beks/economic-parameters'
      preLoaderRoute: typeof BeksEconomicParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneralDataRoute: GeneralDataRoute,
  BeksEconomicParametersRoute: BeksEconomicParametersRoute,
  BeksSummaryOfResultsRoute: BeksSummaryOfResultsRoute,
  BeksTechnicalParametersRoute: BeksTechnicalParametersRoute,
  DsrEconomicParametersRoute: DsrEconomicParametersRoute,
  DsrSummaryOfResultsRoute: DsrSummaryOfResultsRoute,
  DsrTechnicalParametersRoute: DsrTechnicalParametersRoute,
  P2gEconomicParametersRoute: P2gEconomicParametersRoute,
  P2gSummaryOfResultsRoute: P2gSummaryOfResultsRoute,
  P2gTechnicalParametersRoute: P2gTechnicalParametersRoute,
  P2hEconomicParametersRoute: P2hEconomicParametersRoute,
  P2hSummaryOfResultsRoute: P2hSummaryOfResultsRoute,
  P2hTechnicalParametersRoute: P2hTechnicalParametersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
