/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicalParametersP2hRouteImport } from './routes/technical-parameters-p2h'
import { Route as TechnicalParametersP2gRouteImport } from './routes/technical-parameters-p2g'
import { Route as TechnicalParametersBeksRouteImport } from './routes/technical-parameters-beks'
import { Route as SummaryOfResultsP2hRouteImport } from './routes/summary-of-results-p2h'
import { Route as SummaryOfResultsP2gRouteImport } from './routes/summary-of-results-p2g'
import { Route as SummaryOfResultsBeksRouteImport } from './routes/summary-of-results-beks'
import { Route as GeneralDataRouteImport } from './routes/general-data'
import { Route as EconomicParametersP2hRouteImport } from './routes/economic-parameters-p2h'
import { Route as EconomicParametersP2gRouteImport } from './routes/economic-parameters-p2g'
import { Route as EconomicParametersBeksRouteImport } from './routes/economic-parameters-beks'
import { Route as IndexRouteImport } from './routes/index'

const TechnicalParametersP2hRoute = TechnicalParametersP2hRouteImport.update({
  id: '/technical-parameters-p2h',
  path: '/technical-parameters-p2h',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalParametersP2gRoute = TechnicalParametersP2gRouteImport.update({
  id: '/technical-parameters-p2g',
  path: '/technical-parameters-p2g',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalParametersBeksRoute = TechnicalParametersBeksRouteImport.update({
  id: '/technical-parameters-beks',
  path: '/technical-parameters-beks',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryOfResultsP2hRoute = SummaryOfResultsP2hRouteImport.update({
  id: '/summary-of-results-p2h',
  path: '/summary-of-results-p2h',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryOfResultsP2gRoute = SummaryOfResultsP2gRouteImport.update({
  id: '/summary-of-results-p2g',
  path: '/summary-of-results-p2g',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryOfResultsBeksRoute = SummaryOfResultsBeksRouteImport.update({
  id: '/summary-of-results-beks',
  path: '/summary-of-results-beks',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralDataRoute = GeneralDataRouteImport.update({
  id: '/general-data',
  path: '/general-data',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicParametersP2hRoute = EconomicParametersP2hRouteImport.update({
  id: '/economic-parameters-p2h',
  path: '/economic-parameters-p2h',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicParametersP2gRoute = EconomicParametersP2gRouteImport.update({
  id: '/economic-parameters-p2g',
  path: '/economic-parameters-p2g',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicParametersBeksRoute = EconomicParametersBeksRouteImport.update({
  id: '/economic-parameters-beks',
  path: '/economic-parameters-beks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/economic-parameters-beks': typeof EconomicParametersBeksRoute
  '/economic-parameters-p2g': typeof EconomicParametersP2gRoute
  '/economic-parameters-p2h': typeof EconomicParametersP2hRoute
  '/general-data': typeof GeneralDataRoute
  '/summary-of-results-beks': typeof SummaryOfResultsBeksRoute
  '/summary-of-results-p2g': typeof SummaryOfResultsP2gRoute
  '/summary-of-results-p2h': typeof SummaryOfResultsP2hRoute
  '/technical-parameters-beks': typeof TechnicalParametersBeksRoute
  '/technical-parameters-p2g': typeof TechnicalParametersP2gRoute
  '/technical-parameters-p2h': typeof TechnicalParametersP2hRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/economic-parameters-beks': typeof EconomicParametersBeksRoute
  '/economic-parameters-p2g': typeof EconomicParametersP2gRoute
  '/economic-parameters-p2h': typeof EconomicParametersP2hRoute
  '/general-data': typeof GeneralDataRoute
  '/summary-of-results-beks': typeof SummaryOfResultsBeksRoute
  '/summary-of-results-p2g': typeof SummaryOfResultsP2gRoute
  '/summary-of-results-p2h': typeof SummaryOfResultsP2hRoute
  '/technical-parameters-beks': typeof TechnicalParametersBeksRoute
  '/technical-parameters-p2g': typeof TechnicalParametersP2gRoute
  '/technical-parameters-p2h': typeof TechnicalParametersP2hRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/economic-parameters-beks': typeof EconomicParametersBeksRoute
  '/economic-parameters-p2g': typeof EconomicParametersP2gRoute
  '/economic-parameters-p2h': typeof EconomicParametersP2hRoute
  '/general-data': typeof GeneralDataRoute
  '/summary-of-results-beks': typeof SummaryOfResultsBeksRoute
  '/summary-of-results-p2g': typeof SummaryOfResultsP2gRoute
  '/summary-of-results-p2h': typeof SummaryOfResultsP2hRoute
  '/technical-parameters-beks': typeof TechnicalParametersBeksRoute
  '/technical-parameters-p2g': typeof TechnicalParametersP2gRoute
  '/technical-parameters-p2h': typeof TechnicalParametersP2hRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/economic-parameters-beks'
    | '/economic-parameters-p2g'
    | '/economic-parameters-p2h'
    | '/general-data'
    | '/summary-of-results-beks'
    | '/summary-of-results-p2g'
    | '/summary-of-results-p2h'
    | '/technical-parameters-beks'
    | '/technical-parameters-p2g'
    | '/technical-parameters-p2h'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/economic-parameters-beks'
    | '/economic-parameters-p2g'
    | '/economic-parameters-p2h'
    | '/general-data'
    | '/summary-of-results-beks'
    | '/summary-of-results-p2g'
    | '/summary-of-results-p2h'
    | '/technical-parameters-beks'
    | '/technical-parameters-p2g'
    | '/technical-parameters-p2h'
  id:
    | '__root__'
    | '/'
    | '/economic-parameters-beks'
    | '/economic-parameters-p2g'
    | '/economic-parameters-p2h'
    | '/general-data'
    | '/summary-of-results-beks'
    | '/summary-of-results-p2g'
    | '/summary-of-results-p2h'
    | '/technical-parameters-beks'
    | '/technical-parameters-p2g'
    | '/technical-parameters-p2h'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EconomicParametersBeksRoute: typeof EconomicParametersBeksRoute
  EconomicParametersP2gRoute: typeof EconomicParametersP2gRoute
  EconomicParametersP2hRoute: typeof EconomicParametersP2hRoute
  GeneralDataRoute: typeof GeneralDataRoute
  SummaryOfResultsBeksRoute: typeof SummaryOfResultsBeksRoute
  SummaryOfResultsP2gRoute: typeof SummaryOfResultsP2gRoute
  SummaryOfResultsP2hRoute: typeof SummaryOfResultsP2hRoute
  TechnicalParametersBeksRoute: typeof TechnicalParametersBeksRoute
  TechnicalParametersP2gRoute: typeof TechnicalParametersP2gRoute
  TechnicalParametersP2hRoute: typeof TechnicalParametersP2hRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technical-parameters-p2h': {
      id: '/technical-parameters-p2h'
      path: '/technical-parameters-p2h'
      fullPath: '/technical-parameters-p2h'
      preLoaderRoute: typeof TechnicalParametersP2hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-parameters-p2g': {
      id: '/technical-parameters-p2g'
      path: '/technical-parameters-p2g'
      fullPath: '/technical-parameters-p2g'
      preLoaderRoute: typeof TechnicalParametersP2gRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-parameters-beks': {
      id: '/technical-parameters-beks'
      path: '/technical-parameters-beks'
      fullPath: '/technical-parameters-beks'
      preLoaderRoute: typeof TechnicalParametersBeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary-of-results-p2h': {
      id: '/summary-of-results-p2h'
      path: '/summary-of-results-p2h'
      fullPath: '/summary-of-results-p2h'
      preLoaderRoute: typeof SummaryOfResultsP2hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary-of-results-p2g': {
      id: '/summary-of-results-p2g'
      path: '/summary-of-results-p2g'
      fullPath: '/summary-of-results-p2g'
      preLoaderRoute: typeof SummaryOfResultsP2gRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary-of-results-beks': {
      id: '/summary-of-results-beks'
      path: '/summary-of-results-beks'
      fullPath: '/summary-of-results-beks'
      preLoaderRoute: typeof SummaryOfResultsBeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-data': {
      id: '/general-data'
      path: '/general-data'
      fullPath: '/general-data'
      preLoaderRoute: typeof GeneralDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economic-parameters-p2h': {
      id: '/economic-parameters-p2h'
      path: '/economic-parameters-p2h'
      fullPath: '/economic-parameters-p2h'
      preLoaderRoute: typeof EconomicParametersP2hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economic-parameters-p2g': {
      id: '/economic-parameters-p2g'
      path: '/economic-parameters-p2g'
      fullPath: '/economic-parameters-p2g'
      preLoaderRoute: typeof EconomicParametersP2gRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economic-parameters-beks': {
      id: '/economic-parameters-beks'
      path: '/economic-parameters-beks'
      fullPath: '/economic-parameters-beks'
      preLoaderRoute: typeof EconomicParametersBeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EconomicParametersBeksRoute: EconomicParametersBeksRoute,
  EconomicParametersP2gRoute: EconomicParametersP2gRoute,
  EconomicParametersP2hRoute: EconomicParametersP2hRoute,
  GeneralDataRoute: GeneralDataRoute,
  SummaryOfResultsBeksRoute: SummaryOfResultsBeksRoute,
  SummaryOfResultsP2gRoute: SummaryOfResultsP2gRoute,
  SummaryOfResultsP2hRoute: SummaryOfResultsP2hRoute,
  TechnicalParametersBeksRoute: TechnicalParametersBeksRoute,
  TechnicalParametersP2gRoute: TechnicalParametersP2gRoute,
  TechnicalParametersP2hRoute: TechnicalParametersP2hRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
